services:
  - type: web
    name: iirs-protocol-playbook
    runtime: python
    rootDir: iirs_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
